In [1]:
!pip install git+https://github.com/ssut/py-hanspell.git

  Cloning https://github.com/ssut/py-hanspell.git to c:\users\munbe\appdata\local\temp\pip-req-build-x6dik00h


  Running command git clone -q https://github.com/ssut/py-hanspell.git 'C:\Users\munbe\AppData\Local\Temp\pip-req-build-x6dik00h'
  ERROR: Error [WinError 2] 지정된 파일을 찾을 수 없습니다 while executing command git clone -q https://github.com/ssut/py-hanspell.git 'C:\Users\munbe\AppData\Local\Temp\pip-req-build-x6dik00h'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?


In [2]:
from pykospacing import spacing

new_sent = sent.replace(" ", '') # 띄어쓰기가 없는 문장으로 만들기
print(new_sent)

ModuleNotFoundError: No module named 'pykospacing'

In [3]:
!pip install pykospacing

ERROR: Could not find a version that satisfies the requirement pykospacing (from versions: none)
ERROR: No matching distribution found for pykospacing


In [4]:
!pip install kss

In [5]:
import kss
str2 = "나는 너무 힘들다 내가 사는 것이 힘든것이 아니다.나를 힘들게 하는 것은 추위이다. 그러나 좋은 친구 한명만 있어도 힘이 될것 같다"
for str_result in kss.split_sentences(str2):
    print(str_result)

[Korean Sentence Splitter]: Initializing Pynori...


나는 너무 힘들다
내가 사는 것이 힘든것이 아니다.
나를 힘들게 하는 것은 추위이다.
그러나 좋은 친구 한명만 있어도 힘이 될것 같다


In [6]:
!pip install konlpy

In [7]:
from konlpy.tag import Okt


In [8]:
import numpy as np
import tensorflow as tf

x=[]
y=[]
for i in range(10):
  temp = []
  for j in range(i,i+4):
    temp.append(([j/10]))
  x.append(temp)
  y.append((i+4)/10)

print(x, y)

X = np.array(x)
Y = np.array(y)

for i in range(len(X)):
  print(X[i], Y[i])

[[[0.0], [0.1], [0.2], [0.3]], [[0.1], [0.2], [0.3], [0.4]], [[0.2], [0.3], [0.4], [0.5]], [[0.3], [0.4], [0.5], [0.6]], [[0.4], [0.5], [0.6], [0.7]], [[0.5], [0.6], [0.7], [0.8]], [[0.6], [0.7], [0.8], [0.9]], [[0.7], [0.8], [0.9], [1.0]], [[0.8], [0.9], [1.0], [1.1]], [[0.9], [1.0], [1.1], [1.2]]] [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3]
[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9
[[0.6]
 [0.7]
 [0.8]
 [0.9]] 1.0
[[0.7]
 [0.8]
 [0.9]
 [1. ]] 1.1
[[0.8]
 [0.9]
 [1. ]
 [1.1]] 1.2
[[0.9]
 [1. ]
 [1.1]
 [1.2]] 1.3


In [9]:
rnn1 = tf.keras.layers.SimpleRNN(units=1, activation='tanh', return_sequences=True) #units : 레이어의 뉴런 수

model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4,1]),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 10)                120       
                                                                 
 dense (Dense)               (None, 1)                 11        
                                                                 
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.fit(X,Y, epochs=5000, verbose=0)
print(model.predict(X))

1/1 [==============================] - 0s 169ms/step
[[0.39934006]
 [0.5008952 ]
 [0.6005867 ]
 [0.6997266 ]
 [0.7992193 ]
 [0.8994035 ]
 [1.0001109 ]
 [1.1008123 ]
 [1.2007681 ]
 [1.2991538 ]]


In [11]:
print(model.predict(np.array([[[101.1], [101.2], [101.3], [101.4]]])))
print(model.predict(np.array([[[110.5], [110.6], [110.7], [110.8]]])))

1/1 [==============================] - 0s 19ms/step
[[2.832284]]
1/1 [==============================] - 0s 18ms/step
[[2.8356514]]


In [12]:
import numpy
import tensorflow as tf
from numpy import array
from keras.preprocessing.text import Tokenizer, text_to_word_sequence
from keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences


text = '나는 돈을 모아서 인생 드라마인 나의 아저씨 대본집을 샀다'

result = tf.keras.preprocessing.text.text_to_word_sequence(text)
print(text)
print(result)

나는 돈을 모아서 인생 드라마인 나의 아저씨 대본집을 샀다
['나는', '돈을', '모아서', '인생', '드라마인', '나의', '아저씨', '대본집을', '샀다']


In [13]:
docs = ['우리가 인공지능을 공부하는 것은 인공지능 모델을 만드는 것이다',
       '인공지능 모델을 만드는 것은 많은 학습을 거쳐야지 만들 수 있다.',
       '학습을 많이 할 수록 인공지능 모델의 성능은 좋아지고 더 좋은 인공지능 모델을 만들수 있다.',
       ]
 
token = Tokenizer()             # 토큰화 함수 지정
token.fit_on_texts(docs)       # 토큰화 함수에 문장 적용
 
print('1 : ',token.word_counts) # 단어 갯수 출력
print('2 : ', token.document_count) #document 갯수 출력
print('3 : ', token.word_docs) #단어가 포함된 문장의 갯수 출력
print('4 : ',  token.word_index) #단어별 인덱스

1 :  OrderedDict([('우리가', 1), ('인공지능을', 1), ('공부하는', 1), ('것은', 2), ('인공지능', 4), ('모델을', 3), ('만드는', 2), ('것이다', 1), ('많은', 1), ('학습을', 2), ('거쳐야지', 1), ('만들', 1), ('수', 1), ('있다', 2), ('많이', 1), ('할', 1), ('수록', 1), ('모델의', 1), ('성능은', 1), ('좋아지고', 1), ('더', 1), ('좋은', 1), ('만들수', 1)])
2 :  3
3 :  defaultdict(<class 'int'>, {'우리가': 1, '모델을': 3, '인공지능을': 1, '만드는': 2, '인공지능': 3, '것이다': 1, '것은': 2, '공부하는': 1, '만들': 1, '있다': 2, '거쳐야지': 1, '많은': 1, '수': 1, '학습을': 2, '수록': 1, '좋은': 1, '좋아지고': 1, '모델의': 1, '더': 1, '성능은': 1, '만들수': 1, '할': 1, '많이': 1})
4 :  {'인공지능': 1, '모델을': 2, '것은': 3, '만드는': 4, '학습을': 5, '있다': 6, '우리가': 7, '인공지능을': 8, '공부하는': 9, '것이다': 10, '많은': 11, '거쳐야지': 12, '만들': 13, '수': 14, '많이': 15, '할': 16, '수록': 17, '모델의': 18, '성능은': 19, '좋아지고': 20, '더': 21, '좋은': 22, '만들수': 23}


In [14]:
from keras.layers import Dense,Flatten,Embedding

docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요",
        "글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0])

# 토큰화 
token = Tokenizer()
token.fit_on_texts(docs)
print('1 : ',token.word_index)
print('2 : ',token.texts_to_sequences(docs)) #토큰 인덱스를 이용하여 텍스트의 리스트 생성

x = token.texts_to_sequences(docs)
# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.
padded_x =pad_sequences(x, 4)  
print("3 : ", padded_x) #행렬의 행과 렬을 맞추기 위하여 4개의 원소로 표현
 
#임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index)+1
 
#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 10, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20, verbose=0)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

1 :  {'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}
2 :  [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]
3 :  [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]
1/1 [==============================] - 0s 144ms/step - loss: 0.6529 - accuracy: 0.9000

 Accuracy: 0.9000


In [15]:
from keras.layers import Dense,Flatten,Embedding

docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요",
        "글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0])

# 토큰화 
token = Tokenizer()
token.fit_on_texts(docs)
print('1 : ',token.word_index)
print('2 : ',token.texts_to_sequences(docs)) #토큰 인덱스를 이용하여 텍스트의 리스트 생성

x = token.texts_to_sequences(docs)
# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.
padded_x =pad_sequences(x, 4)  
print("3 : ", padded_x) #행렬의 행과 렬을 맞추기 위하여 4개의 원소로 표현
 
#임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index)+1
 
#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 10, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20, verbose=0)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

1 :  {'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}
2 :  [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]
3 :  [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]
1/1 [==============================] - 0s 158ms/step - loss: 0.6379 - accuracy: 0.9000

 Accuracy: 0.9000


In [19]:
import numpy
import tensorflow as tf
import matplotlib.pyplot as plt

from keras.datasets import reuters #로이터 뉴스 셋 불러오기
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding
from keras.utils import np_utils
from tensorflow.keras.preprocessing.sequence import pad_sequences

(X_train, Y_train), (X_test, Y_test) = reuters.load_data(num_words=10000, test_split=0.2)

category = numpy.max(Y_train) + 1
print("Category : ",category,)
print("Learnning Data : ",len(X_train))
print("Testing Data : ",len(X_test))

x_train = sequence.pad_sequences(X_train, maxlen=100) #단어의 수를 100개로 결정
x_test = sequence.pad_sequences(X_test, maxlen=100)
y_train = np_utils.to_categorical(Y_train) #one-hot encoding
y_test = np_utils.to_categorical(Y_test)

model = Sequential()
model.add(Embedding(1000, 100)) #불러온 단어의 총 갯수, 기사당 단어의 수
model.add(LSTM(100, activation='tanh')) #기사당 단어의 수
model.add(Dense(46, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=100, epochs=40, validation_data=(x_test, y_test), verbose=0)

# 테스트 정확도 출력
print("\nAccuracy: %.4f" % (model.evaluate(x_test, y_test)[1]))

# 오차
y_vloss = history.history['val_loss']
y_loss = history.history['loss']

x_len = numpy.arange(len(y_loss))
plt.plot(x_len, y_vloss, marker='.', c="red", label='Testset_loss')
plt.plot(x_len, y_loss, marker='.', c="blue", label='Trainset_loss')
plt.legend(loc='upper right')
plt.grid()
plt.xlabel('epoch')
plt.ylabel('loss')
plt.show()



Category :  46
Learnning Data :  8982
Testing Data :  2246


AttributeError: module 'keras.preprocessing.sequence' has no attribute 'pad_sequences'