In [9]:
import tensorflow as tf
import numpy as np

- pip install tensorflow 로 설치가능
- 그래도 안될 시 jupyter 업데이트 진행
- pip install -upgrade pip #업데이트

- data는 정형, 비정형
- 정형data는 쉽게 머신러닝을 사용할 수 있지만, 비정형 data는 그렇지 못한다.
- 비정형data = 사진, 텍스트, 음성 등 수치로 나타내기 힘든 data들
- 비정형data -> 정형data로 만드는 작업이 딥러닝에서 중요한 이슈
- 사진이나, 음성, text 등을 정형data로 만드는 것은 숫자로 만드는 것
- 0, 1 숫자로 표현을 해서 컴퓨터에게 학습시키는 것
- 딥러닝을 이용하려면 이러한 비정형 data를 수치화시켜서 깔끔하게 정리해야 한다.

### data 구조를 살펴보면
- 스칼라, 벡터, 행렬, 텐서가 있는데 모두 션형대수이다.
- 딥러닝 자체가 선형대수를 필수적으로 알면 좋다.

- 스칼라 : 점, 움직이지 않는 방향성이 없는
- 스칼라 1
- 벡터는 1, 2(axis = 0, 1)
- 벡터 1
       2
- 행렬 1, 2
       1, 2
       
- 텐서 1, 2 겹겹이 3차원으로 들어가는 것
       1, 2

In [5]:
1

1

In [6]:
1, 2

(1, 2)

1,2 
1,2

2x2 행렬이 된다.

### 스칼라

In [13]:
a = tf.constant(11)
tf.constant(12)


<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [14]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [15]:
a.numpy() # 해당 텐서플로우 스칼라값을 출력해주는 개념

11

### 벡터
- 1차원의 개념 : 방향성이 생길 수 있다. 행, 열

In [37]:
vec = tf.constant([1,2,3,4])

In [38]:
vec

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [39]:
vec.numpy()

array([1, 2, 3, 4])

### 행렬(Matrix)
- 행과 열을 가능 2차원 배열

In [31]:
c = [[1,2,3,4],
     [3,4,5,6]]

In [32]:
c[0][0]

1

In [33]:
sp_mt = tf.constant([[1,2,3,4],
                     [3,4,5,6]])

In [34]:
sp_mt.numpy()

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [35]:
[[1,2,3,4],
 [3,4,5,6]]

[[1, 2, 3, 4], [3, 4, 5, 6]]

In [36]:
list(sp_mt.numpy())

[array([1, 2, 3, 4]), array([3, 4, 5, 6])]

### 텐서(Tensor)
- 3차원의 개념
- 0차원 스칼라
- 1차원 벡터
- 2차원 행렬
- 3차원 텐서

In [62]:
ten_sp = tf.constant([
    [[1,2,3]],[[4,5,6]],
    [[7,8,9]],[[10,11,12]],
    [[13,14,15],[16,17,18]]
])

ValueError: Can't convert non-rectangular Python sequence to Tensor.

- N차원 tessor
- tensor는 2차원 배열이 겹으로 쌍혀있는 것
- 3차원 텐서를 하나의 스칼라로 본다. 정육면체
- tensor가 스칼라되면
- 정육면체가 2개 쌍이면 4차원의 개념 벡터

### numpy로 만들기

In [46]:
sp1 = np.arange(10)

In [47]:
sp1.ndim

1

In [48]:
sp1.shape

(10,)

### 넘파이로 행렬은 어떻게 만들까?

In [50]:
# reshape 함수를 이용해 만들 수 있다.
# np.reshape(data,(행렬에 필요한 행과 열 지정))
np.reshape(sp1,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
np.reshape(sp1,(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
#3차원도 가능
sp3 = np.arange(0,24,1)

In [56]:
sp3.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [58]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
import pandas as pd